# Generated by Django 4.2.13 on 2026-05-09 22:55

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrchestratorRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('full', 'Full Run'), ('analyse', 'Analyse Only'), ('stops', 'Trailing Stops'), ('wheel', 'Wheel Cycle'), ('watchlist', 'Watchlist'), ('capitol', 'Capitol Trades')], default='full', max_length=20)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('error', 'Error'), ('partial', 'Partial Success')], default='running', max_length=20)),
                ('strategy', models.CharField(blank=True, max_length=30)),
                ('tickers_analysed', models.JSONField(default=list)),
                ('decisions_made', models.IntegerField(default=0)),
                ('orders_placed', models.IntegerField(default=0)),
                ('buy_count', models.IntegerField(default=0)),
                ('sell_count', models.IntegerField(default=0)),
                ('hold_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Orchestrator Run',
                'verbose_name_plural': 'Orchestrator Runs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=20, unique=True)),
                ('qty', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('avg_entry_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('current_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('market_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cost_basis', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('unrealised_pl', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('unrealised_pl_pct', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('stop_loss_floor', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('side', models.CharField(default='long', max_length=10)),
                ('asset_class', models.CharField(default='us_equity', max_length=20)),
                ('last_synced', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Position',
                'verbose_name_plural': 'Positions',
                'ordering': ['-market_value'],
            },
        ),
        migrations.CreateModel(
            name='WheelContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=20)),
                ('stage', models.CharField(choices=[('csp', 'Cash-Secured Put'), ('cc', 'Covered Call')], max_length=5)),
                ('strike', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expiry', models.DateField()),
                ('contracts', models.IntegerField(default=1)),
                ('premium_collected', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cost_basis', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('expired', 'Expired Worthless'), ('assigned', 'Assigned'), ('called_away', 'Called Away'), ('closed', 'Closed Early')], default='open', max_length=20)),
                ('order_id', models.CharField(blank=True, max_length=100)),
                ('ta_rating', models.CharField(blank=True, max_length=20)),
                ('ta_price_target', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('opened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('cycle_profit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Wheel Contract',
                'verbose_name_plural': 'Wheel Contracts',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='CapitolTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('politician', models.CharField(db_index=True, max_length=200)),
                ('party', models.CharField(blank=True, choices=[('D', 'Democrat'), ('R', 'Republican'), ('I', 'Independent')], max_length=1)),
                ('chamber', models.CharField(blank=True, max_length=10)),
                ('ticker', models.CharField(db_index=True, max_length=20)),
                ('transaction_type', models.CharField(default='purchase', max_length=30)),
                ('amount', models.CharField(blank=True, max_length=100)),
                ('amount_min', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('amount_max', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('transaction_date', models.DateField(db_index=True)),
                ('disclosure_date', models.DateField(blank=True, null=True)),
                ('score', models.FloatField(default=0.0)),
                ('analysed', models.BooleanField(db_index=True, default=False)),
                ('ta_rating', models.CharField(blank=True, max_length=20)),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Capitol Trade',
                'verbose_name_plural': 'Capitol Trades',
                'ordering': ['-transaction_date', '-score'],
                'unique_together': {('politician', 'ticker', 'transaction_date', 'transaction_type')},
            },
        ),
        migrations.CreateModel(
            name='TradeDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=20)),
                ('trade_date', models.DateField(db_index=True, default=datetime.date.today)),
                ('rating', models.CharField(choices=[('Buy', 'Buy'), ('Overweight', 'Overweight'), ('Hold', 'Hold'), ('Underweight', 'Underweight'), ('Sell', 'Sell'), ('Error', 'Error')], default='Hold', max_length=20)),
                ('price_target', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('stop_loss', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('position_sizing', models.CharField(blank=True, max_length=100)),
                ('time_horizon', models.CharField(blank=True, max_length=100)),
                ('investment_thesis', models.TextField(blank=True)),
                ('execution_action', models.CharField(blank=True, choices=[('buy', 'Buy'), ('sell', 'Sell'), ('reduce', 'Reduce'), ('hold', 'Hold'), ('dry_run', 'Dry Run'), ('error', 'Error')], max_length=20)),
                ('execution_message', models.TextField(blank=True)),
                ('order_id', models.CharField(blank=True, max_length=100)),
                ('wheel_activated', models.BooleanField(default=False)),
                ('capitol_trade_source', models.BooleanField(default=False)),
                ('source', models.CharField(default='orchestrator', max_length=50)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decisions', to='trading.orchestratorrun')),
            ],
            options={
                'verbose_name': 'Trade Decision',
                'verbose_name_plural': 'Trade Decisions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['ticker', 'trade_date'], name='trading_tra_ticker_8c61c5_idx')],
            },
        ),
    ]
